### ISSUE TITLE
...1小时前更新的GG了...

### ISSUE THREAD

**Issue by onepve** [qkqpttgf/OneDrive_SCF#29]
```
{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"Exception: failed to get access_token. in /var/user/index.php:233\nStack trace:\n#0 /var/user/index.php(81): list_files('/')\n#1 /var/runtime/php7/bootstrap.php(41): main_handler(Array, Array)\n#2 /var/runtime/php7/bootstrap.php(189): __scf_bootstrap_\\EventHandler-\u003ehandle(Object(stdClass), Object(stdClass))\n#3 /var/runtime/php7/bootstrap.php(212): __scf_bootstrap_\\__main_for_scf()\n#4 {main}"}
```
之前20191104正常.下午更新的20191112就炸了.大约在1小时前

**Comment by qkqpttgf** [comment]
呃，这个地方没get到token，可能是TX的网络问题，你刷新一下能好吗？

**Comment by onepve** [comment]
刷新无效...
```
https://d.wxlost.com
```

**Comment by onepve** [comment]
尝试重新安装..第一步就炸了....
```
Error
MissingParameter
The request is missing a required parameter `Region`.

function_name:cloud
Region:
namespace:default
```

**Comment by onepve** [comment]
原来要用默认域名安装....重新安装就好了.感谢大佬的程序

**Comment by legendtang** [comment]
遇到相同的问题，从默认域名安装无解，无论如何获取不到，如何 debug @qkqpttgf

**Comment by qkqpttgf** [comment]
贴你的长链接url，跟显示的带Region的ERROR截图。

**Comment by legendtang** [comment]
返回数据:
```
{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"Exception: failed to get access_token. in /var/user/index.php:215\nStack trace:\n#0 /var/user/index.php(61): list_files('/')\n#1 /var/runtime/php7/bootstrap.php(41): main_handler(Array, Array)\n#2 /var/runtime/php7/bootstrap.php(189): __scf_bootstrap_\\EventHandler-\u003ehandle(Object(stdClass), Object(stdClass))\n#3 /var/runtime/php7/bootstrap.php(212): __scf_bootstrap_\\__main_for_scf()\n#4 {main}"}
```

日志:
```
返回数据:

{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"Exception: failed to get access_token. in /var/user/index.php:215\nStack trace:\n#0 /var/user/index.php(61): list_files('/')\n#1 /var/runtime/php7/bootstrap.php(41): main_handler(Array, Array)\n#2 /var/runtime/php7/bootstrap.php(189): __scf_bootstrap_\\EventHandler-\u003ehandle(Object(stdClass), Object(stdClass))\n#3 /var/runtime/php7/bootstrap.php(212): __scf_bootstrap_\\__main_for_scf()\n#4 {main}"}

日志:

START RequestId: 72a20587-235e-11ea-ba69-5254000dcd5e

Event RequestId: 72a20587-235e-11ea-ba69-5254000dcd5e

{

    "headerParameters": [],

    "headers": {

        "accept": "text\/html,application\/xhtml xml,application\/xml;q=0.9,image\/webp,image\/apng,*\/*;q=0.8,application\/signed-exchange;v=b3;q=0.9",

        "accept-encoding": "gzip, deflate, br",

        "accept-language": "zh-CN,zh;q=0.9,zh-TW;q=0.8,en-US;q=0.7,en;q=0.6",

        "cache-control": "max-age=0",

        "connection": "keep-alive",

        "cookie": "language=",

        "endpoint-timeout": "15",

        "host": "service-ldy6kz42-1251733566.ap-hongkong.apigateway.myqcloud.com",

        "referer": "https:\/\/service-ldy6kz42-1251733566.ap-hongkong.apigateway.myqcloud.com\/release\/onedrive_hk\/?authorization_code&code=OAQABAAIAAACQN9QBRU3jT6bcBQLZNUj7mPhN0z8VLVk0xnTv_3V53T2kYpr-fpkTMNMjvF3ZQjBpwdTockz-lrbi7Z2WCTfI66yNF_oHnyjOhu9bWVXC6zrJ6HlI5Cnx0ATj8VMzRwCQVeZDdTf4h9dnXAaF5yZjCE2h30jIcx1qb8sVYYOLK-W_wQitTo0c60LyFPXK_VffEdx3ZzE42Cw8n-dju7T5OhRNszpZWJq0dU9drpVBUlu4Ok-5f1nyS-L_K3zdh7AwrG_f9ivP9-Ysp9yXtWhZO_DR8adaOk_xTGoR00GIrena9mhfgttgI031WG7blp33dg6oz9Sl4zQKMLzHrvOCWUInoN73Xd8HOagpYjdTN8eSojWpU8WQRb-UFP3o9_tCAOecEpX9ML7kcrmQ_qD0Vbz5p15-vEncfOWDdHnu2bCxHFrYzdkuLlbfcTLuXXcpJ1ArHqV5l3tmoQ_p8Mo76vl-wU-vTtQsDObptbaue0RGMOAUdc7REShO1rW9PFiTWSOkyCS7JygQAbFa9sYeMGXNQx6vwq0qOr9mp9E86kCVdYw9BrACy3DRIc2EpDGv2sevncQ7n0OLr1q1je_TsbADyHe4zQTS7Vl8PnjkYG9UvklBPN4bVHIx-nPxifA5TSim7enW_-Tp9NPIU7ZDQOdJd89Uo-Rxj_VsCR0t8deDbuiFr8n98AJihY7Ud_y0duSACXGl2PVZ-fiaIovZIc9MbXfZb4AOvZU9CyOIwbqik-NVV8te_q--YPy8Hm8D318Ip4-klBykBQjeFdN7IAA",

        "sec-fetch-mode": "navigate",

        "sec-fetch-site": "same-origin",

        "sec-fetch-user": "?1",

        "upgrade-insecure-requests": "1",

        "user-agent": "Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/79.0.3945.88 Safari\/537.36",

        "x-anonymous-consumer": "true",

        "x-qualifier": "$LATEST"

    },

    "httpMethod": "GET",

    "path": "\/onedrive_hk\/",

    "pathParameters": [],

    "queryString": [],

    "queryStringParameters": [],

    "requestContext": {

        "httpMethod": "ANY",

        "identity": [],

        "path": "\/onedrive_hk",

        "serviceId": "service-ldy6kz42",

        "sourceIp": "1.65.179.67",

        "stage": "release"

    }

}

 

{

    "memory_limit_in_mb": 128,

    "time_limit_in_ms": 30000,

    "request_id": "72a20587-235e-11ea-ba69-5254000dcd5e",

    "environ": ";SCF_NAMESPACE=default",

    "function_version": "$LATEST",

    "function_name": "onedrive_hk",

    "namespace": "default"

}

 

failed to get access_token. response{"error":"invalid_grant","error_description":"AADSTS9002313: Invalid request. Request is malformed or invalid.\r\nTrace ID: 1576f68d-713f-4288-833c-1c974a30d200\r\nCorrelation ID: fc32f81e-5b61-4cd8-ab20-6ee90dd13147\r\nTimestamp: 2019-12-20 19:25:14Z","error_codes":[9002313],"timestamp":"2019-12-20 19:25:14Z","trace_id":"1576f68d-713f-4288-833c-1c974a30d200","correlation_id":"fc32f81e-5b61-4cd8-ab20-6ee90dd13147","error_uri":"https:\/\/login.microsoftonline.com\/error?code=9002313"}Exception: failed to get access_token. in /var/user/index.php:215

Stack trace:

#0 /var/user/index.php(61): list_files('/')

#1 /var/runtime/php7/bootstrap.php(41): main_handler(Array, Array)

#2 /var/runtime/php7/bootstrap.php(189): __scf_bootstrap_\EventHandler->handle(Object(stdClass), Object(stdClass))

#3 /var/runtime/php7/bootstrap.php(212): __scf_bootstrap_\__main_for_scf()

#4 {main}

END RequestId: 72a20587-235e-11ea-ba69-5254000dcd5e

Report RequestId: 72a20587-235e-11ea-ba69-5254000dcd5e Duration:38ms Memory:128MB MaxMemoryUsed:25.035156MB
```
![image](https://user-images.githubusercontent.com/1352729/69915570-830e8d00-148b-11ea-85eb-3a830b3cd4de.png)

@qkqpttgf

**Comment by legendtang** [comment]
@qkqpttgf ？这个问题没好哇

**Comment by qkqpttgf** [comment]
重新安装，截图

**Comment by legendtang** [comment]
@qkqpttgf 重装过了，一样报错

https://service-ldy6kz42-1251733566.ap-hongkong.apigateway.myqcloud.com/release/onedrive_hk

```
返回数据:

{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"Exception: failed to get access_token. in /var/user/index.php:215\nStack trace:\n#0 /var/user/index.php(61): list_files('/')\n#1 /var/runtime/php7/bootstrap.php(41): main_handler(Array, Array)\n#2 /var/runtime/php7/bootstrap.php(189): __scf_bootstrap_\\EventHandler-\u003ehandle(Object(stdClass), Object(stdClass))\n#3 /var/runtime/php7/bootstrap.php(212): __scf_bootstrap_\\__main_for_scf()\n#4 {main}"}

日志:

START RequestId: 1dc4423b-2797-11ea-bdf9-5254000dcd5e

Event RequestId: 1dc4423b-2797-11ea-bdf9-5254000dcd5e

{

    "headerParameters": [],

    "headers": {

        "accept": "text\/html,application\/xhtml xml,application\/xml;q=0.9,image\/webp,image\/apng,*\/*;q=0.8,application\/signed-exchange;v=b3;q=0.9",

        "accept-encoding": "gzip, deflate, br",

        "accept-language": "zh-CN,zh;q=0.9,zh-TW;q=0.8,en-US;q=0.7,en;q=0.6",

        "connection": "keep-alive",

        "cookie": "language=",

        "endpoint-timeout": "15",

        "host": "service-ldy6kz42-1251733566.ap-hongkong.apigateway.myqcloud.com",

        "sec-fetch-mode": "navigate",

        "sec-fetch-site": "cross-site",

        "sec-fetch-user": "?1",

        "upgrade-insecure-requests": "1",

        "user-agent": "Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/79.0.3945.88 Safari\/537.36",

        "x-anonymous-consumer": "true",

        "x-qualifier": "$LATEST"

    },

    "httpMethod": "GET",

    "path": "\/onedrive_hk",

    "pathParameters": [],

    "queryString": [],

    "queryStringParameters": [],

    "requestContext": {

        "httpMethod": "ANY",

        "identity": [],

        "path": "\/onedrive_hk",

        "serviceId": "service-ldy6kz42",

        "sourceIp": "175.159.121.71",

        "stage": "release"

    }

}

 

{

    "memory_limit_in_mb": 128,

    "time_limit_in_ms": 30000,

    "request_id": "1dc4423b-2797-11ea-bdf9-5254000dcd5e",

    "environ": ";SCF_NAMESPACE=default",

    "function_version": "$LATEST",

    "function_name": "onedrive_hk",

    "namespace": "default"

}

 

failed to get access_token. response{"error":"invalid_grant","error_description":"AADSTS9002313: Invalid request. Request is malformed or invalid.\r\nTrace ID: f094c879-ceaf-4b3e-896e-c08513627701\r\nCorrelation ID: de1f576f-128a-4884-a81d-2459640599bf\r\nTimestamp: 2019-12-26 04:20:59Z","error_codes":[9002313],"timestamp":"2019-12-26 04:20:59Z","trace_id":"f094c879-ceaf-4b3e-896e-c08513627701","correlation_id":"de1f576f-128a-4884-a81d-2459640599bf","error_uri":"https:\/\/login.microsoftonline.com\/error?code=9002313"}Exception: failed to get access_token. in /var/user/index.php:215

Stack trace:

#0 /var/user/index.php(61): list_files('/')

#1 /var/runtime/php7/bootstrap.php(41): main_handler(Array, Array)

#2 /var/runtime/php7/bootstrap.php(189): __scf_bootstrap_\EventHandler->handle(Object(stdClass), Object(stdClass))

#3 /var/runtime/php7/bootstrap.php(212): __scf_bootstrap_\__main_for_scf()

#4 {main}

END RequestId: 1dc4423b-2797-11ea-bdf9-5254000dcd5e

Report RequestId: 1dc4423b-2797-11ea-bdf9-5254000dcd5e Duration:356ms Memory:128MB MaxMemoryUsed:40.320312MB
```

**Comment by qkqpttgf** [comment]
删掉函数，新建一个看看

**Comment by legendtang** [comment]
> 删掉函数，新建一个看看

确实试过多次无效了，包括重新建立 API 网关、删掉函数。我这边 Oneindex 是正常的，以前这个项目也可以用，不知道什么原因

**Comment by langren1353** [comment]
我也遇到这个bug了，研究了半天发现，居然出现了t8环境变量，但是代码中只到了t7，于是手动代码中加上t8的代码，就可以了，希望排查一下
![](https://www.png8.com/imgs/2020/01/70cd92ad8bc763d8.png)

**Comment by qkqpttgf** [comment]
> 我也遇到这个bug了，研究了半天发现，居然出现了t8环境变量，但是代码中只到了t7，于是手动代码中加上t8的代码，就可以了，希望排查一下

你的ID跟KEY没打码，请去腾讯那边删掉ID跟KEY，再重新生成新的！
SCF的环境变量不知道什么时候改了，已经可以存放超过128字节的东西了，我下次就不切开了，直接存整个。
对了，你的是什么帐号？一般个人帐号到t4，A1帐号到t7，你的怎么会到t8的。

**Comment by langren1353** [comment]
copy。原因未知
我的是E5账号，hostloc上他们给的。。。
不知道为什么长度超了
